### ISSUE TITLE
Compilation issue with the commit 1f7fbeb

### ISSUE THREAD

**Issue by OrpheeGT** [exynos5420/android_device_samsung_exynos5420-common#1]
Hello,

I had to revert the commit because of a compilation issue.

The following folder is missing on my local branch : 
$(LOCAL_PATH)/../../../../packages/resources/devicesettings/res

Did I miss something ?
Thank you

**Comment by deadman96385** [comment]
https://github.com/exynos5420/manifests/commit/d60737f706e27e6e5cfbf1582abe600f6a022e66

Add that repo
