### ISSUE TITLE
Little question

### ISSUE THREAD

**Issue by AlperHuda** [exynos5420/android_device_samsung_exynos5420-common#3]
Sorry, i am already asked that question but i will ask one more thing, i am always checking the news about pie for exynos5420 devices with exynos5420 gerrit and github changes but i cant see any n1awifi(SM-P600) changes, you was say " Yes. We are working on bringing up all the devices to the latest.". when will your team start for another devices like n1awifi? Also what bugs left? Can you say something about that process ? I am big fan this project .Good luck, thanks and sorry again.

**Comment by thompatry** [comment]
I do not have a n1a device. I am working on v1a/v2a since I have those devices. Once I have that, I will work on n1a and have some people test it out.

**Comment by AlperHuda** [comment]
Okay if you have telegram account i can join and test thanks again

**Comment by thompatry** [comment]
Please send an email to teamexynos5420@gmail.com and we can talk more there.

**Comment by AlperHuda** [comment]
Okay i sent you a message i will wait your answer  :)
